import { NavigationPath } from '../types';

export const ROUTES = {
  OVERVIEW: 'overview' as NavigationPath,
  BUILDINGS: 'buildings' as NavigationPath,
  ADD_BUILDING: 'add-building' as NavigationPath,
  EDIT_BUILDING: 'edit-building' as NavigationPath,
  FLOORS: 'floors' as NavigationPath,
  ROOM_TYPES: 'room-types' as NavigationPath,
  ADD_ROOM_TYPE: 'add-room-type' as NavigationPath,
  EDIT_ROOM_TYPE: 'edit-room-type' as NavigationPath,
  ROOMS: 'rooms' as NavigationPath,
  ADD_ROOM: 'add-room' as NavigationPath,
  BULK_ADD_ROOMS: 'bulk-add-rooms' as NavigationPath,
  EDIT_ROOM: 'edit-room' as NavigationPath,
  ROOM_STATUS: 'room-status' as NavigationPath,
  TAXES: 'taxes' as NavigationPath,
  TAX_CONFIGURATION: 'tax-configuration' as NavigationPath,
  ADD_TAX: 'add-tax' as NavigationPath,
  EDIT_TAX: 'edit-tax' as NavigationPath,
  ADD_TAX_RATE: 'add-tax-rate' as NavigationPath,
  DOCUMENT_TYPES: 'document-types' as NavigationPath,
  OTHER_CHARGES: 'other-charges' as NavigationPath,
  OTHER_CHARGES_CATEGORIES: 'other-charges-categories' as NavigationPath,
  MEASUREMENT_UNITS: 'measurement-units' as NavigationPath,
  PAYMENT_TYPES: 'payment-types' as NavigationPath,
  EXCHANGE_RATES: 'exchange-rates' as NavigationPath,
  POLICIES: 'policies' as NavigationPath,
  GUEST_CATEGORIES: 'guest-categories' as NavigationPath,
  USER_MANAGEMENT: 'user-management' as NavigationPath,
  EMAIL_TEMPLATES: 'email-templates' as NavigationPath,
  ROLES_PRIVILEGES: 'roles-privileges' as NavigationPath,
  GENERAL_SETTINGS: 'general-settings' as NavigationPath,
  GUEST_MANDATORY_DATA: 'guest-mandatory-data' as NavigationPath,
  DEVICE_CONFIGURATION: 'device-configuration' as NavigationPath,
  CRS_TAX_EXEMPT: 'crs-tax-exempt' as NavigationPath,
} as const;
