import {
  ReservationRecord,
  GuestLedgerEntry,
  FolioTransaction,
  BatchFolioItem,
  RoomRackCard,
  RoomBlockItem,
  GroupBookingMaster,
  RoomCommentItem,
  RoomHardwareSpecs,
} from './types';

export const WORKING_DATE = '29-Jun-2026';
export const PROPERTY_NAME = 'Grand Plaza Hotel';
export const PROPERTY_SUBTITLE = 'Grand Metropole Resort & Spa';

// SCREEN 1: Search Reservation Mock Data
export const INITIAL_RESERVATIONS: ReservationRecord[] = [
  {
    id: '1',
    resId: 'RES-9481',
    crsNumber: 'SYX-88219',
    guestName: 'Eleanor Vance-Moreau',
    guestEmail: 'eleanor.vance@vancemedia.com',
    guestPhone: '+1 (415) 555-0192',
    vipTier: 'VIP 1',
    roomNumber: '101',
    roomCategory: 'DLXK',
    roomCategoryName: 'Deluxe King',
    floor: 'Floor 1 (Garden)',
    wing: 'North Wing',
    checkInDate: '29-Jun-2026',
    checkOutDate: '02-Jul-2026',
    nights: 3,
    etaNote: 'ETA 14:30 Arrived',
    channelSource: 'Direct Web',
    ratePlan: 'Best Available Rate (BAR)',
    totalAmount: 645.0,
    paidAmount: 645.0,
    balanceDue: 0.0,
    status: 'Checked In',
    notes: 'Late arrival requested, airport limousine pick-up confirmed.',
  },
  {
    id: '2',
    resId: 'RES-9482',
    crsNumber: 'BKNG-401931',
    guestName: 'Robert Thorne',
    guestEmail: 'rthorne@techconsult.org',
    guestPhone: '+1 (206) 555-0814',
    vipTier: 'Repeat Guest',
    roomNumber: '204',
    roomCategory: 'EXST',
    roomCategoryName: 'Executive Suite',
    floor: 'Floor 2 (North)',
    wing: 'Tower East',
    checkInDate: '29-Jun-2026',
    checkOutDate: '04-Jul-2026',
    nights: 5,
    etaNote: 'ETA 18:00 Flight DL804',
    channelSource: 'Booking.com',
    ratePlan: 'Corporate Negotiated Tier 1',
    totalAmount: 1240.0,
    paidAmount: 300.0,
    balanceDue: 940.0,
    status: 'Confirmed',
    notes: 'High floor away from elevators preferred.',
  },
  {
    id: '3',
    resId: 'RES-9445',
    crsNumber: 'DIR-88120',
    guestName: 'Sophia Lin-Zimmerman',
    guestEmail: 'sophia.lin@apexcapital.co',
    guestPhone: '+1 (312) 555-9921',
    vipTier: 'VIP 2',
    roomNumber: '310',
    roomCategory: 'PRMS',
    roomCategoryName: 'Presidential Suite',
    floor: 'Floor 4',
    wing: 'Penthouse',
    checkInDate: '25-Jun-2026',
    checkOutDate: '29-Jun-2026',
    nights: 4,
    etaNote: 'Dep Due (11:00 AM)',
    channelSource: 'Direct Web',
    ratePlan: 'VIP Club Luxury Rate',
    totalAmount: 3420.0,
    paidAmount: 3420.0,
    balanceDue: 0.0,
    status: 'Departing',
    notes: 'Express checkout requested, luggage pickup arranged with Bell Captain.',
  },
  {
    id: '4',
    resId: 'RES-9410',
    crsNumber: 'EXP-29103',
    guestName: 'Marcus Kraus',
    guestEmail: 'm.kraus@berlin-advisors.de',
    guestPhone: '+49 30 20930',
    roomNumber: 'Unassigned',
    roomCategory: 'SUPQ',
    roomCategoryName: 'Superior Queen',
    floor: 'South Wing',
    wing: 'South Wing',
    checkInDate: '30-Jun-2026',
    checkOutDate: '03-Jul-2026',
    nights: 3,
    channelSource: 'Expedia Partner',
    ratePlan: 'Weekend Getaway Package',
    totalAmount: 510.0,
    paidAmount: 510.0,
    balanceDue: 0.0,
    status: 'Cancelled',
    notes: 'Cancelled 28-Jun. Refund processed per 48-hr policy.',
  },
  {
    id: '5',
    resId: 'RES-9490',
    crsNumber: 'CORP-AR-8802',
    guestName: 'David Harrison (Aviation Summit)',
    guestEmail: 'dharrison@boeing.com',
    guestPhone: '+1 (206) 555-4491',
    vipTier: 'VIP 1',
    roomNumber: '412',
    roomCategory: 'DLXK',
    roomCategoryName: 'Deluxe King',
    floor: 'Floor 4',
    wing: 'Tower West',
    checkInDate: '29-Jun-2026',
    checkOutDate: '02-Jul-2026',
    nights: 3,
    etaNote: 'ETA 19:45 Shuttle 2',
    channelSource: 'Corporate Direct AR',
    ratePlan: 'Aviation Summit Master Billing',
    totalAmount: 825.0,
    paidAmount: 0.0,
    balanceDue: 825.0,
    status: 'Confirmed',
    notes: 'Direct AR bill to corporate account GRP-2026-AV. Room and tax covered.',
  },
  {
    id: '6',
    resId: 'RES-9502',
    crsNumber: 'WLK-0922',
    guestName: 'Anita Lopez',
    guestEmail: 'anita.lopez@gmail.com',
    guestPhone: '+1 (702) 555-8120',
    vipTier: 'AAA Member',
    roomNumber: '208',
    roomCategory: 'DLXK',
    roomCategoryName: 'Deluxe King',
    floor: 'Floor 2 (South)',
    wing: 'Tower East',
    checkInDate: '29-Jun-2026',
    checkOutDate: '30-Jun-2026',
    nights: 1,
    etaNote: 'Checked-in Front Desk',
    channelSource: 'Front Desk Walk-in',
    ratePlan: 'AAA Member Discount',
    totalAmount: 215.0,
    paidAmount: 215.0,
    balanceDue: 0.0,
    status: 'Checked In',
    notes: 'Walk-in registered by Alex Rivera. Credit card pre-auth completed.',
  },
  {
    id: '7',
    resId: 'RES-9511',
    crsNumber: 'SYX-89304',
    guestName: 'Raymond Chen',
    guestEmail: 'rchen@apexglobal.tech',
    guestPhone: '+1 (650) 555-0182',
    roomNumber: 'Unassigned',
    roomCategory: 'DLXK',
    roomCategoryName: 'Deluxe King',
    floor: 'Tower West',
    wing: 'Tower West',
    checkInDate: '30-Jun-2026',
    checkOutDate: '04-Jul-2026',
    nights: 4,
    channelSource: 'Corporate Direct AR',
    ratePlan: 'Corporate Negotiated Tier 1',
    totalAmount: 960.0,
    paidAmount: 0.0,
    balanceDue: 960.0,
    status: 'Confirmed',
    notes: 'Apex Global Summit delegate. Room allocation pending.',
  },
  {
    id: '8',
    resId: 'RES-9520',
    crsNumber: 'OTA-77312',
    guestName: 'Julian Wright',
    guestEmail: 'j.wright@wrightlaw.com',
    guestPhone: '+1 (212) 555-9011',
    vipTier: 'Repeat Guest',
    roomNumber: '114',
    roomCategory: 'DLXK',
    roomCategoryName: 'Deluxe King',
    floor: 'Floor 1',
    wing: 'North Wing',
    checkInDate: '27-Jun-2026',
    checkOutDate: '29-Jun-2026',
    nights: 2,
    etaNote: 'Departing Today',
    channelSource: 'Direct Web',
    ratePlan: 'Best Available Rate (BAR)',
    totalAmount: 590.0,
    paidAmount: 590.0,
    balanceDue: 0.0,
    status: 'Departing',
    notes: 'Early breakfast order fulfilled.',
  },
];

// SCREEN 2: Guest Ledger Mock Data
export const INITIAL_LEDGER_ENTRIES: GuestLedgerEntry[] = [
  {
    id: '1',
    guestName: 'Sophia Rodriguez',
    folioId: '94102',
    vipTier: 'VIP Diamond',
    phone: '+1 (555) 438-9920',
    email: 's.rodriguez@luxurycapital.com',
    roomNumber: '204',
    floor: 'Fl 2',
    roomCategory: 'DLXK',
    checkInDate: '27-Jun-2026',
    checkOutDate: '30-Jun-2026',
    adr: 245.0,
    paidAmount: 490.0,
    balanceDue: 0.0,
    specialRequests: ['Feather-free synthetic pillows', 'Complimentary parking', 'High floor'],
    status: 'In-House',
  },
  {
    id: '2',
    guestName: 'Marcus Thorne',
    folioId: '94118',
    vipTier: 'Corp Exec',
    phone: '+1 (555) 782-1139',
    email: 'm.thorne@thornebio.co',
    roomNumber: '412',
    floor: 'Fl 4',
    roomCategory: 'EXST',
    checkInDate: '28-Jun-2026',
    checkOutDate: '02-Jul-2026',
    adr: 310.0,
    paidAmount: 310.0,
    balanceDue: 620.0,
    specialRequests: ['Airport shuttle 18:00', 'Minibar replenish daily'],
    status: 'In-House',
  },
  {
    id: '3',
    guestName: 'Elena Rostova',
    folioId: '94129',
    vipTier: 'VIP Platinum',
    phone: '+44 20 7946 0991',
    email: 'e.rostova@londonpartners.uk',
    roomNumber: '501',
    floor: 'Fl 5',
    roomCategory: 'PRMS',
    checkInDate: '25-Jun-2026',
    checkOutDate: '29-Jun-2026',
    adr: 450.0,
    paidAmount: 1800.0,
    balanceDue: 0.0,
    specialRequests: ['Late Checkout 14:00 Approved', 'Champagne welcome kit'],
    status: 'In-House',
    approvedDeparture: '14:00 PM (+3 hrs)',
    lateFeeStatus: 'Waived (Tier Privilege)',
    authorizedBy: 'Alex Rivera (FD Sup)',
    hkSyncStatus: 'HK Board Updated',
  },
  {
    id: '4',
    guestName: 'David & Linda Kim',
    folioId: '94135',
    vipTier: 'Standard',
    phone: '+1 (555) 309-8812',
    email: 'dkim@veritascapital.com',
    roomNumber: '114',
    floor: 'Fl 1',
    roomCategory: 'SUPQ',
    checkInDate: '26-Jun-2026',
    checkOutDate: '01-Jul-2026',
    adr: 185.0,
    paidAmount: 555.0,
    balanceDue: 370.0,
    specialRequests: ['Baby crib installed (HK verified)', 'Extra towels daily'],
    status: 'In-House',
  },
  {
    id: '5',
    guestName: 'Victoria Sterling',
    folioId: '94142',
    vipTier: 'VIP Diamond',
    phone: '+1 (555) 902-8321',
    email: 'vsterling@sterlingventures.com',
    roomNumber: '108',
    targetRoomNumber: '312',
    floor: 'Fl 1 → Fl 3',
    roomCategory: 'DLXK → PRMS',
    checkInDate: '26-Jun-2026',
    checkOutDate: '03-Jul-2026',
    adr: 280.0,
    paidAmount: 840.0,
    balanceDue: 0.0,
    specialRequests: ['Move 11:30 AM Pending', 'Bell Captain coordination'],
    status: 'In-House',
    transitionType: 'Comp Upgrade',
    moveTime: '11:30 AM',
    baggageHandling: 'Bell Desk Notified (2 Bags)',
    hkStatus: 'Pending HK Final Inspect',
  },
  {
    id: '6',
    guestName: 'Jonathan Vance',
    folioId: '94188',
    vipTier: 'Corporate',
    phone: '+1 (555) 891-2300',
    email: 'jvance@apexholdings.com',
    roomNumber: '214',
    targetRoomNumber: '220',
    floor: 'Fl 2',
    roomCategory: 'SUPQ',
    checkInDate: '28-Jun-2026',
    checkOutDate: '02-Jul-2026',
    adr: 210.0,
    paidAmount: 420.0,
    balanceDue: 0.0,
    status: 'In-House',
    transitionType: 'Maintenance Swap',
    moveTime: '12:00 PM',
    baggageHandling: 'Guest Self-Handling',
    hkStatus: 'Inspected & Clean Ready',
  },
  {
    id: '7',
    guestName: 'Haruto Takahashi',
    folioId: '94195',
    vipTier: 'Standard',
    phone: '+81 3 5555 0149',
    email: 'h.takahashi@tokyofinance.jp',
    roomNumber: '102',
    targetRoomNumber: '105',
    floor: 'Fl 1',
    roomCategory: 'DLXK',
    checkInDate: '28-Jun-2026',
    checkOutDate: '01-Jul-2026',
    adr: 230.0,
    paidAmount: 460.0,
    balanceDue: 0.0,
    status: 'In-House',
    transitionType: 'Connecting Room Req',
    moveTime: '13:15 PM',
    baggageHandling: 'Pending Departure Room 105',
    hkStatus: 'Dirty — Prior Guest In',
  },
  {
    id: '8',
    guestName: 'Camilla Dubois',
    folioId: '94208',
    vipTier: 'VIP Gold',
    phone: '+33 1 4050 6070',
    email: 'c.dubois@parisluxe.fr',
    roomNumber: '403',
    targetRoomNumber: '504',
    floor: 'Fl 4 → Fl 5',
    roomCategory: 'EXST → PRMS',
    checkInDate: '27-Jun-2026',
    checkOutDate: '04-Jul-2026',
    adr: 340.0,
    paidAmount: 1020.0,
    balanceDue: 90.0,
    status: 'In-House',
    transitionType: 'Paid Upgrade',
    moveTime: '14:00 PM',
    baggageHandling: 'Bell Desk Storage #B-19',
    hkStatus: 'Inspected & Clean Ready',
  },
  {
    id: '9',
    guestName: 'Liam Hemsworth',
    folioId: '94215',
    vipTier: 'Standard',
    phone: '+1 (310) 555-7721',
    email: 'lhemsworth@filmmakers.com',
    roomNumber: '305',
    floor: 'Fl 3',
    roomCategory: 'DLXK',
    checkInDate: '26-Jun-2026',
    checkOutDate: '29-Jun-2026',
    adr: 220.0,
    paidAmount: 490.0,
    balanceDue: 0.0,
    status: 'To Check Out',
    approvedDeparture: '13:30 PM (+2.5 hrs)',
    lateFeeStatus: '$50.00 Applied to Folio',
    authorizedBy: 'Alex Rivera (FD Sup)',
    hkSyncStatus: 'HK Board Updated',
  },
  {
    id: '10',
    guestName: 'Claire Beaumont',
    folioId: '94220',
    vipTier: 'Repeat Guest',
    phone: '+1 (514) 555-8833',
    email: 'claire.b@montrealdesign.ca',
    roomNumber: '218',
    floor: 'Fl 2',
    roomCategory: 'SUPQ',
    checkInDate: '27-Jun-2026',
    checkOutDate: '29-Jun-2026',
    adr: 195.0,
    paidAmount: 440.0,
    balanceDue: 0.0,
    status: 'To Check Out',
    approvedDeparture: '14:00 PM (+3 hrs)',
    lateFeeStatus: '$50.00 Applied to Folio',
    authorizedBy: 'Rachel Morgan (FD)',
    hkSyncStatus: 'HK Board Updated',
  },
];

export const SAMPLE_FOLIO_TRANSACTIONS: FolioTransaction[] = [
  { id: '1', date: '27-Jun', description: 'Room Charge - Standard Rate', debit: 260.0, credit: 0 },
  { id: '2', date: '27-Jun', description: 'Municipal Lodging Surcharge (7%)', debit: 18.2, credit: 0 },
  { id: '3', date: '28-Jun', description: 'Room Charge - Standard Rate', debit: 260.0, credit: 0 },
  { id: '4', date: '28-Jun', description: 'Municipal Lodging Surcharge (7%)', debit: 18.2, credit: 0 },
  { id: '5', date: '28-Jun', description: 'The Verandah Lounge - #T14 Signed', debit: 88.6, credit: 0 },
  { id: '6', date: '29-Jun', description: 'Pre-Authorized Visa (...8104) Settled', debit: 0, credit: 645.0 },
];

// SCREEN 3: Batch Folio Mock Data
export const INITIAL_BATCH_FOLIOS: BatchFolioItem[] = [
  {
    id: '1',
    resId: 'RES-8841',
    folioId: 'FOL-2026-1102',
    guestName: 'Eleanor Vance',
    guestEmail: 'e.vance@apexgroup.com',
    roomNumber: '101',
    roomCategory: 'DLXK',
    checkInDate: '27-Jun',
    checkOutDate: '29-Jun',
    nights: 2,
    stayCategory: 'Due Out',
    totalAmount: 645.0,
    balanceDue: 0.0,
    dispatchStatus: 'Folio Generated',
    selected: true,
  },
  {
    id: '2',
    resId: 'RES-8843',
    folioId: 'FOL-2026-1103',
    guestName: 'Marcus Thorne',
    guestEmail: 'm.thorne@thornebio.co',
    roomNumber: '304',
    roomCategory: 'PRMS',
    checkInDate: '25-Jun',
    checkOutDate: '29-Jun',
    nights: 4,
    stayCategory: 'Due Out',
    totalAmount: 1420.5,
    balanceDue: 0.0,
    dispatchStatus: 'Emailed',
    dispatchNote: 'Emailed 08:30 AM',
    selected: true,
  },
  {
    id: '3',
    resId: 'RES-8850',
    folioId: 'FOL-2026-1104',
    guestName: 'Sofia Chen',
    guestEmail: 'sofia.chen@pacifictech.io',
    roomNumber: '512',
    roomCategory: 'DLXQ',
    checkInDate: '28-Jun',
    checkOutDate: '29-Jun',
    nights: 1,
    stayCategory: 'Due Out',
    totalAmount: 310.0,
    balanceDue: 0.0,
    dispatchStatus: 'Reg Form Ready',
    selected: true,
  },
  {
    id: '4',
    resId: 'RES-8856',
    folioId: 'FOL-2026-1105',
    guestName: 'David Kim',
    guestEmail: 'dkim@veritascapital.com',
    roomNumber: '208',
    roomCategory: 'EXE-K',
    checkInDate: '26-Jun',
    checkOutDate: '29-Jun',
    nights: 3,
    stayCategory: 'Due Out',
    totalAmount: 980.2,
    balanceDue: 0.0,
    dispatchStatus: 'Unprinted',
    selected: true,
  },
  {
    id: '5',
    resId: 'RES-8861',
    folioId: 'FOL-2026-1106',
    guestName: 'Brigitte Laurent',
    guestEmail: 'blaurent@luxallure.fr',
    roomNumber: '415',
    roomCategory: 'VLLA',
    checkInDate: '22-Jun',
    checkOutDate: '29-Jun',
    nights: 7,
    stayCategory: 'Due Out',
    totalAmount: 3120.0,
    balanceDue: 0.0,
    dispatchStatus: 'Folio Generated',
    selected: true,
  },
  {
    id: '6',
    resId: 'RES-8865',
    folioId: 'FOL-2026-1107',
    guestName: 'Hamad Al-Maktoum',
    guestEmail: 'h.almaktoum@gulfventures.ae',
    roomNumber: 'PH-01',
    roomCategory: 'PENT',
    checkInDate: '24-Jun',
    checkOutDate: '29-Jun',
    nights: 5,
    stayCategory: 'Due Out',
    totalAmount: 5400.0,
    balanceDue: 0.0,
    dispatchStatus: 'Emailed',
    dispatchNote: 'Emailed 07:45 AM',
    selected: true,
  },
  {
    id: '7',
    resId: 'RES-8872',
    folioId: 'FOL-2026-1108',
    guestName: 'Aaliyah Rossi',
    guestEmail: 'a.rossi@milano-style.it',
    roomNumber: '219',
    roomCategory: 'SUPK',
    checkInDate: '26-Jun',
    checkOutDate: '29-Jun',
    nights: 3,
    stayCategory: 'Due Out',
    totalAmount: 820.0,
    balanceDue: 0.0,
    dispatchStatus: 'Unprinted',
    selected: true,
  },
  {
    id: '8',
    resId: 'RES-8880',
    folioId: 'FOL-2026-1109',
    guestName: 'Julian Wright',
    guestEmail: 'j.wright@wrightlaw.com',
    roomNumber: '114',
    roomCategory: 'DLXK',
    checkInDate: '27-Jun',
    checkOutDate: '29-Jun',
    nights: 2,
    stayCategory: 'Due Out',
    totalAmount: 590.0,
    balanceDue: 0.0,
    dispatchStatus: 'Folio Generated',
    selected: true,
  },
];

// SCREEN 4: Change Room Status Mock Data
export const INITIAL_ROOM_CARDS: RoomRackCard[] = [
  // Floor 1
  {
    id: '101',
    roomNumber: '101',
    floor: 1,
    wing: 'Wing A',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    status: 'VC',
    isOccupied: false,
    cleanedTime: 'Cleaned 08:30 AM',
    hkAttendant: 'Maria Santos',
  },
  {
    id: '102',
    roomNumber: '102',
    floor: 1,
    wing: 'Wing A',
    roomType: 'SUPQ',
    roomTypeName: 'Superior Queen',
    status: 'VD',
    isOccupied: false,
    occupancyDetail: 'Checkout 10:15 AM',
    hkAttendant: 'Unassigned',
  },
  {
    id: '103',
    roomNumber: '103',
    floor: 1,
    wing: 'Wing A',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    status: 'OC',
    isOccupied: true,
    guestName: 'Elena Rostova (Dep Today)',
    cleanedTime: 'Daily Clean 09:15 AM',
    hkAttendant: 'T. Chen',
  },
  {
    id: '104',
    roomNumber: '104',
    floor: 1,
    wing: 'Wing A',
    roomType: 'EXST',
    roomTypeName: 'Executive Suite',
    status: 'VC',
    isOccupied: false,
    cleanedTime: 'Cleaned Yesterday',
    hkAttendant: 'L. Kowalski',
  },
  {
    id: '108',
    roomNumber: '108',
    floor: 1,
    wing: 'Wing A',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    status: 'OD',
    isOccupied: true,
    guestName: 'Eleanor Vance (Stayover)',
    occupancyDetail: 'Refresh Req • 09:45 AM',
    hkAttendant: 'Elena V.',
    isFocusRoom: true,
  },
  {
    id: '109',
    roomNumber: '109',
    floor: 1,
    wing: 'Wing A',
    roomType: 'SUPQ',
    roomTypeName: 'Superior Queen',
    status: 'OOO',
    isOccupied: false,
    maintenanceNote: 'HVAC Maintenance • ETA: 30-Jun 14:00',
    hkAttendant: 'Eng: Robert D.',
  },
  // Floor 2
  {
    id: '201',
    roomNumber: '201',
    floor: 2,
    wing: 'Wing A',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    status: 'VC',
    isOccupied: false,
    cleanedTime: 'Cleaned 11:20 AM',
    hkAttendant: 'L. Kowalski',
  },
  {
    id: '202',
    roomNumber: '202',
    floor: 2,
    wing: 'Wing A',
    roomType: 'EXST',
    roomTypeName: 'Executive Suite',
    status: 'OC',
    isOccupied: true,
    guestName: 'Marcus Thorne (Stayover)',
    cleanedTime: 'Cleaned 09:30 AM',
    hkAttendant: 'Maria Santos',
  },
  {
    id: '203',
    roomNumber: '203',
    floor: 2,
    wing: 'Wing A',
    roomType: 'SUPQ',
    roomTypeName: 'Superior Queen',
    status: 'VD',
    isOccupied: false,
    occupancyDetail: 'Wait Time: 45 min',
    hkAttendant: 'In Progress',
  },
  {
    id: '204',
    roomNumber: '204',
    floor: 2,
    wing: 'Wing B',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    status: 'VC',
    isOccupied: false,
    cleanedTime: 'Cleaned 10:40 AM',
    hkAttendant: 'T. Chen',
  },
  {
    id: '205',
    roomNumber: '205',
    floor: 2,
    wing: 'Wing B',
    roomType: 'SUPQ',
    roomTypeName: 'Superior Queen',
    status: 'OC',
    isOccupied: true,
    guestName: 'Sarah Jenkins (Arr Today)',
    cleanedTime: 'Checked In 08:15 AM',
    hkAttendant: 'Completed',
  },
  {
    id: '206',
    roomNumber: '206',
    floor: 2,
    wing: 'Wing B',
    roomType: 'EXST',
    roomTypeName: 'Executive Suite',
    status: 'VC',
    isOccupied: false,
    cleanedTime: 'Cleaned 09:10 AM',
    hkAttendant: 'L. Kowalski',
  },
];

// SCREEN 5: Block Room Mock Data
export const INITIAL_ROOM_BLOCKS: RoomBlockItem[] = [
  {
    id: '1',
    roomNumber: '109',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    floor: 'Floor 1',
    wing: 'Wing A',
    category: 'HVAC Repair',
    categoryType: 'OOO',
    fromDateTime: '29-Jun-2026 • 10:00',
    toDateTime: '02-Jul-2026 • 18:00',
    durationString: '3d 8h',
    remarks: 'Compressor coil replacement. Authorized by Facilities Mgr Dave K.',
    overlapWarning: {
      resId: 'RES-9620',
      guestName: 'David Harrison',
      checkInTime: '01-Jul-2026 15:00',
    },
    blockedBy: 'Alex Rivera',
    blockedByRole: 'Front Desk Lead',
    isActive: true,
  },
  {
    id: '2',
    roomNumber: '204',
    roomType: 'EXST',
    roomTypeName: 'Executive Suite',
    floor: 'Floor 2',
    wing: 'Wing B',
    category: 'Deep Carpet Sanitization',
    categoryType: 'OOS',
    fromDateTime: '28-Jun-2026 • 14:00',
    toDateTime: '30-Jun-2026 • 12:00',
    durationString: '1d 22h',
    remarks: 'Scheduled quarterly steam sanitization following pet checkout.',
    blockedBy: 'Maria Santos',
    blockedByRole: 'Exec Housekeeper',
    isActive: true,
  },
  {
    id: '3',
    roomNumber: '315',
    roomType: 'DLXK',
    roomTypeName: 'Deluxe King',
    floor: 'Floor 3',
    wing: 'Corner',
    category: 'Plumbing Overhaul',
    categoryType: 'OOO',
    fromDateTime: '27-Jun-2026 • 09:00',
    toDateTime: '03-Jul-2026 • 17:00',
    durationString: '6d 8h',
    remarks: 'Main shower valve leak under tub surround. Vendor parts awaiting.',
    blockedBy: 'Dave Kowalski',
    blockedByRole: 'Facilities Director',
    isActive: true,
  },
  {
    id: '4',
    roomNumber: '402',
    roomType: 'PRES',
    roomTypeName: 'Presidential Suite',
    floor: 'Floor 4',
    wing: 'Penthouse',
    category: 'Executive Hold',
    categoryType: 'OOS',
    fromDateTime: '29-Jun-2026 • 08:00',
    toDateTime: '05-Jul-2026 • 12:00',
    durationString: '6d 4h',
    remarks: 'Reserved for Board of Directors visit unassigned placeholder.',
    blockedBy: 'Elena Rostova',
    blockedByRole: 'General Manager',
    isActive: true,
  },
  {
    id: '5',
    roomNumber: '118',
    roomType: 'STDQ',
    roomTypeName: 'Standard Queen',
    floor: 'Floor 1',
    wing: 'Wing C',
    category: 'Painting Touch-up',
    categoryType: 'OOS',
    fromDateTime: '25-Jun-2026 • 09:00',
    toDateTime: '28-Jun-2026 • 16:00',
    durationString: 'Completed',
    remarks: 'Baseboard and entry hallway repaint. Dry time cleared early.',
    blockedBy: 'Dave Kowalski',
    blockedByRole: 'Facilities',
    isActive: false,
  },
];

// SCREEN 6: Edit Group Mock Data
export const INITIAL_GROUP_MASTER: GroupBookingMaster = {
  id: 'GRP-1',
  groupId: 'GRP-2026-088',
  groupName: 'Apex Global Annual Summit 2026',
  corporateAccountName: 'Apex Global Holdings LLC',
  directArCode: 'AR-APX-992',
  primaryOrganizer: 'Eleanor Vance',
  organizerPhone: '+1 (212) 555-0144',
  checkInDate: '28-Jun-2026',
  checkOutDate: '04-Jul-2026',
  cutOffDate: '20-Jun-2026',
  cutOffStatus: 'Released / Locked',
  masterBillingFolio: 'FOL-GRP-088',
  totalBilled: 24650.0,
  creditHeadroom: 32450.0,
  creditLineCap: 50000.0,
  creditUtilizationPercent: 43.5,
  enforcedRoutingDirective: {
    roomAndTax: 'Routed automatically to Master Corporate Folio (FOL-GRP-088).',
    incidentals: 'Routed to individual guest personal folio with required credit pre-auth.',
  },
  membersCount: 8,
  contractedBlocks: 35,
  members: [
    {
      id: 'm1',
      resId: 'RES-9481',
      guestName: 'Eleanor Vance',
      guestEmail: 'e.vance@apexholdings.com',
      vipTier: 'VIP 1',
      roomNumber: '101',
      roomType: 'DLXK',
      roomTypeName: 'Deluxe King',
      checkInDate: '28-Jun',
      checkOutDate: '04-Jul',
      status: 'In-House',
      billingCoverage: 'Room & Tax Covered',
    },
    {
      id: 'm2',
      resId: 'RES-9482',
      guestName: 'Marcus Thorne',
      guestEmail: 'mthorne@apexglobal.tech',
      roomNumber: '204',
      roomType: 'EXST',
      roomTypeName: 'Executive Suite',
      checkInDate: '28-Jun',
      checkOutDate: '02-Jul',
      status: 'In-House',
      billingCoverage: 'Room & Tax Covered',
    },
    {
      id: 'm3',
      resId: 'RES-9490',
      guestName: 'David Harrison',
      guestEmail: 'dharrison@apex-partners.com',
      roomNumber: '412',
      roomType: 'DLXK',
      roomTypeName: 'Deluxe King',
      checkInDate: '29-Jun',
      checkOutDate: '03-Jul',
      status: 'Confirmed',
      billingCoverage: 'Room & Tax Covered',
    },
    {
      id: 'm4',
      resId: 'RES-9502',
      guestName: 'Anita Lopez',
      guestEmail: 'anita.lopez@apexholdings.com',
      roomNumber: '208',
      roomType: 'SUPQ',
      roomTypeName: 'Superior Queen',
      checkInDate: '28-Jun',
      checkOutDate: '01-Jul',
      status: 'In-House',
      billingCoverage: 'Self-Pay All',
    },
    {
      id: 'm5',
      resId: 'RES-9511',
      guestName: 'Raymond Chen',
      guestEmail: 'rchen@apexglobal.tech',
      roomNumber: 'Unassigned',
      roomType: 'DLXK',
      roomTypeName: 'Deluxe King',
      checkInDate: '30-Jun',
      checkOutDate: '04-Jul',
      status: 'Confirmed',
      billingCoverage: 'Room & Tax Covered',
    },
  ],
};

// SCREEN 7: Room Comments Mock Data
export const INITIAL_ROOM_COMMENTS: RoomCommentItem[] = [
  {
    id: '1',
    commentId: 'LOG-2906-8841',
    authorName: 'Elena Rostova',
    authorRole: 'Head Housekeeper',
    authorDepartment: 'Housekeeping',
    authorInitials: 'ER',
    terminal: 'HK-04',
    category: 'Housekeeping',
    timestamp: 'Today, 29-Jun • 10:15 AM',
    content:
      'Completed interim towel replacement and minibar replenishment. Guest requested fresh Nespresso pods and feather pillows checked. No maintenance issues detected.',
    verifiedBadge: 'Verified by HK Inspect',
  },
  {
    id: '2',
    commentId: 'LOG-2906-8790',
    authorName: 'Alex Rivera',
    authorRole: 'Front Desk Supervisor',
    authorDepartment: 'Front Desk',
    authorInitials: 'AR',
    terminal: 'FD-01',
    category: 'Front Desk Note',
    timestamp: 'Today, 29-Jun • 08:30 AM',
    content:
      'Guest called Front Desk requesting scheduled room relocation to Presidential Suite #312 for 11:30 AM. Luggage transfer coordinates sent to Bell Desk lead Dave.',
    isUrgentAlert: true,
  },
  {
    id: '3',
    commentId: 'LOG-2806-7412',
    authorName: 'Marcus Chen',
    authorRole: 'Lead Technician',
    authorDepartment: 'Engineering',
    authorInitials: 'MC',
    terminal: 'BMS Gateway',
    category: 'Maintenance',
    timestamp: 'Yesterday, 28-Jun • 15:45 PM',
    content:
      'Thermostat calibrated and air filter replaced during pre-arrival inspection. Ambient temperature set to 21°C as per VIP preference note.',
    verifiedBadge: 'Work Order #WO-4903 Closed',
  },
  {
    id: '4',
    commentId: 'LOG-2806-6992',
    authorName: 'Sarah Jenkins',
    authorRole: 'Front Desk Agent',
    authorDepartment: 'Front Desk',
    authorInitials: 'SJ',
    terminal: 'FD-03',
    category: 'Guest Preference',
    timestamp: '28-Jun-2026 • 13:20 PM',
    content:
      'Pre-arrival welcome fruit basket and champagne delivery verified in room prior to guest arrival.',
    verifiedBadge: 'Amenity Kit Order #AK-110',
  },
];

export const ROOM_108_HARDWARE_SPECS: RoomHardwareSpecs = {
  roomNumber: '108',
  roomType: 'Deluxe King (DLXK)',
  floor: 1,
  tower: 'North Tower',
  currentStatus: 'Occupied Dirty (OD)',
  currentGuest: 'Eleanor Vance',
  stayRange: '28-Jun → 04-Jul',
  keycardLock: {
    model: 'VingCard RFID',
    batteryLevel: 94,
  },
  minibarScale: {
    status: 'Auto-Bar Sense (Active Ping)',
  },
  hvacController: {
    model: 'EcoTemp Pro',
    targetTemp: '21.0°C',
    ambientTemp: '21.4°C',
  },
  lastSanitized: '28-Jun 11:20',
  cleanCert: 'Clean Cert. A+',
  departmentVolumes: {
    frontDesk: 12,
    housekeeping: 8,
    maintenance: 4,
  },
  checklist: [
    { task: 'VIP Fruit & Welcome Card', status: 'DONE' },
    { task: 'Feather-Free Pillow Substitution', status: 'DONE' },
    { task: 'Suite #312 Relocation at 11:30', status: 'PENDING' },
  ],
};
