import { GuestRecord, CommercialContact, ContactCategory, LostFoundItem } from './types';

export const INITIAL_GUESTS: GuestRecord[] = [
  {
    id: 'GST-992014',
    title: 'Dr.',
    firstName: 'Elena',
    middleName: 'M.',
    lastName: 'Rostova-Hughes',
    suffix: 'PhD',
    birthDate: '1984-04-12',
    gender: 'Female',
    nationality: 'United States',
    company: 'Hughes Biotechnology AG',
    designation: 'Chief Scientific Officer',
    department: 'Genomics R&D',
    remarks: 'Prefers high floor quiet suite, hypoallergenic pillows, extra sparkling water, and late checkout when available.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'VIP Tier 1 • Chairman Club',
    createdDate: '14-Mar-2022',
    totalStays: 14,
    totalNights: 42,
    totalSpend: 18420,
    lastVisit: '18-Jan-2026',
    lastRoom: 'Suite 1402 (Presidential)',
    inHouse: true,
    contacts: [
      {
        id: 'CNT-992014-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+1 (415) 890-2194',
        countryCode: '+1',
        email: 'elena.rostova@hughes-bio.com',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: '742 Montgomery St, Penthouse B',
        city: 'San Francisco',
        state: 'CA',
        zip: '94111',
        country: 'United States',
      },
      {
        id: 'CNT-992014-02',
        isPrimary: false,
        contactType: 'Office / Executive Assistant',
        phone: '+1 (650) 492-8800',
        countryCode: '+1',
        email: 'assistant-ea@hughes-bio.com',
        folioDispatch: false,
        addressType: 'Corporate HQ',
        street: '1200 Innovation Parkway, Suite 400',
        city: 'Palo Alto',
        state: 'CA',
        zip: '94304',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'DOC-992014-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'USA-P98421098',
        validTill: '2031-08-24',
        nameOnDocument: 'ELENA MARIE ROSTOVA-HUGHES',
        issuedBy: 'United States Department of State',
        issuePlace: 'Washington D.C., USA',
        registeredAddress: {
          street: '742 Montgomery St, Penthouse B',
          city: 'San Francisco',
          state: 'CA',
          zip: '94111',
          country: 'United States',
        },
        remarks: 'MRZ and biometric microchip verified by front desk passport scanner on 18-Jan-2026.',
        isOcrVerified: true,
      },
      {
        id: 'DOC-992014-02',
        isPrimary: false,
        documentType: 'Driver License',
        documentNumber: 'DL-CA-9482109',
        validTill: '2028-04-12',
        nameOnDocument: 'ELENA M ROSTOVA-HUGHES',
        issuedBy: 'California DMV',
        issuePlace: 'Sacramento, CA',
        registeredAddress: {
          street: '742 Montgomery St, Penthouse B',
          city: 'San Francisco',
          state: 'CA',
          zip: '94111',
          country: 'United States',
        },
        remarks: 'Secondary photo ID registered during vehicle parking registration.',
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992015',
    title: 'Mr.',
    firstName: 'Klaus',
    lastName: 'Schulze',
    birthDate: '1979-11-03',
    gender: 'Male',
    nationality: 'Germany',
    company: 'German Embassy Cultural Section',
    designation: 'Diplomatic Attaché',
    department: 'Foreign Affairs',
    remarks: 'Requires official diplomatic VAT exemption documentation upon check-in.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'Diplomatic Priority',
    createdDate: '10-Feb-2023',
    totalStays: 8,
    totalNights: 29,
    totalSpend: 11350,
    lastVisit: '12-Feb-2026',
    lastRoom: 'Room 804 (Deluxe King)',
    inHouse: false,
    contacts: [
      {
        id: 'CNT-992015-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+49 171 4928104',
        countryCode: '+49',
        email: 'klaus.schulze@diplo-de.org',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'Unter den Linden 42',
        city: 'Berlin',
        state: 'Berlin',
        zip: '10117',
        country: 'Germany',
      },
    ],
    documents: [
      {
        id: 'DOC-992015-01',
        isPrimary: true,
        documentType: 'Diplomatic ID',
        documentNumber: 'DEU-DIP-491028',
        validTill: '2029-05-15',
        nameOnDocument: 'KLAUS SCHULZE',
        issuedBy: 'Auswärtiges Amt',
        issuePlace: 'Berlin, Germany',
        registeredAddress: {
          street: 'Unter den Linden 42',
          city: 'Berlin',
          state: 'Berlin',
          zip: '10117',
          country: 'Germany',
        },
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992016',
    title: 'Sheikh',
    firstName: 'Tariq',
    middleName: 'H.',
    lastName: 'Al-Rahman',
    birthDate: '1975-06-20',
    gender: 'Male',
    nationality: 'United Arab Emirates',
    company: 'Al-Rahman Equity Partners',
    designation: 'Managing Partner',
    department: 'Executive Office',
    remarks: 'Royal & VIP protocol: requires private airport transfer and halal dining arrangements.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'VIP Tier 1 • Chairman Club',
    createdDate: '05-Jan-2021',
    totalStays: 22,
    totalNights: 86,
    totalSpend: 44900,
    lastVisit: '02-Mar-2026',
    lastRoom: 'Penthouse Royal Suite',
    inHouse: true,
    contacts: [
      {
        id: 'CNT-992016-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+971 50 8291048',
        countryCode: '+971',
        email: 'tariq@alrahman-equity.ae',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'Al Wasl Road, Villa 18',
        city: 'Dubai',
        state: 'Dubai',
        zip: '00000',
        country: 'United Arab Emirates',
      },
    ],
    documents: [
      {
        id: 'DOC-992016-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'ARE-P49201824',
        validTill: '2030-10-10',
        nameOnDocument: 'TARIQ HASSAN AL-RAHMAN',
        issuedBy: 'Ministry of Interior',
        issuePlace: 'Abu Dhabi, UAE',
        registeredAddress: {
          street: 'Al Wasl Road, Villa 18',
          city: 'Dubai',
          state: 'Dubai',
          zip: '00000',
          country: 'United Arab Emirates',
        },
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992017',
    title: 'Ms.',
    firstName: 'Yuka',
    lastName: 'Tanaka',
    birthDate: '1990-09-15',
    gender: 'Female',
    nationality: 'Japan',
    company: 'Tanaka Media Ltd',
    designation: 'Senior VP Creative',
    department: 'Digital Arts',
    remarks: 'Quiet corner room preferred; green tea kettle setup in room.',
    dnrStatus: 'none',
    isVip: false,
    vipTier: 'Gold Preferred',
    createdDate: '19-Aug-2023',
    totalStays: 5,
    totalNights: 14,
    totalSpend: 6720,
    lastVisit: '28-Dec-2025',
    lastRoom: 'Room 612 (Executive King)',
    inHouse: false,
    contacts: [
      {
        id: 'CNT-992017-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+81 90 4920 1829',
        countryCode: '+81',
        email: 'yuka.tanaka@tanakamedia.co.jp',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'Minami-Aoyama 5-7-2',
        city: 'Minato-ku',
        state: 'Tokyo',
        zip: '107-0062',
        country: 'Japan',
      },
    ],
    documents: [
      {
        id: 'DOC-992017-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'JPN-TZ492810',
        validTill: '2032-02-18',
        nameOnDocument: 'YUKA TANAKA',
        issuedBy: 'Ministry of Foreign Affairs',
        issuePlace: 'Tokyo, Japan',
        registeredAddress: {
          street: 'Minami-Aoyama 5-7-2',
          city: 'Minato-ku',
          state: 'Tokyo',
          zip: '107-0062',
          country: 'Japan',
        },
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992018',
    title: 'Mr.',
    firstName: 'Oliver',
    lastName: 'Bennett',
    birthDate: '1988-03-27',
    gender: 'Male',
    nationality: 'United Kingdom',
    remarks: 'Disputed bar tab in Nov 2025. Mandatory credit card pre-authorization required on check-in.',
    dnrStatus: 'warning',
    dnrReason: 'Late payment dispute & unauthorized mini-bar charges settled after checkout. Requires manager pre-approval.',
    incidentRef: 'INC-2025-0819',
    isVip: false,
    createdDate: '14-Nov-2024',
    totalStays: 2,
    totalNights: 3,
    totalSpend: 850,
    lastVisit: '14-Nov-2025',
    lastRoom: 'Room 310 (Standard Queen)',
    inHouse: false,
    contacts: [
      {
        id: 'CNT-992018-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+44 7700 900481',
        countryCode: '+44',
        email: 'oliver.bennett88@gmail.com',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: '14 Kensington High St',
        city: 'London',
        state: 'Greater London',
        zip: 'W8 4PT',
        country: 'United Kingdom',
      },
    ],
    documents: [
      {
        id: 'DOC-992018-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'GBR-948210984',
        validTill: '2029-11-20',
        nameOnDocument: 'OLIVER CHARLES BENNETT',
        issuedBy: 'HM Passport Office',
        issuePlace: 'London, UK',
        registeredAddress: {
          street: '14 Kensington High St',
          city: 'London',
          state: 'Greater London',
          zip: 'W8 4PT',
          country: 'United Kingdom',
        },
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992019',
    title: 'Ms.',
    firstName: 'Sofia',
    lastName: 'Alvarez',
    birthDate: '1982-12-05',
    gender: 'Female',
    nationality: 'Spain',
    company: 'Alvarez Global Logistics',
    designation: 'CEO',
    remarks: 'Prefers feather pillows and early check-in at 11:00 AM.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'VIP Tier 2',
    createdDate: '22-Jun-2022',
    totalStays: 11,
    totalNights: 35,
    totalSpend: 16800,
    lastVisit: '14-Sep-2026',
    lastRoom: 'Room 810 (Executive King)',
    inHouse: true,
    contacts: [
      {
        id: 'CNT-992019-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+34 612 345 678',
        countryCode: '+34',
        email: 'sofia.alvarez@alvarez-logistics.es',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'Paseo de la Castellana 89',
        city: 'Madrid',
        state: 'Madrid',
        zip: '28046',
        country: 'Spain',
      },
    ],
    documents: [
      {
        id: 'DOC-992019-01',
        isPrimary: true,
        documentType: 'National Identity Card',
        documentNumber: 'ESP-DNI-48291048X',
        validTill: '2030-07-30',
        nameOnDocument: 'SOFIA MARIA ALVAREZ',
        issuedBy: 'Ministerio del Interior',
        issuePlace: 'Madrid, Spain',
        registeredAddress: {
          street: 'Paseo de la Castellana 89',
          city: 'Madrid',
          state: 'Madrid',
          zip: '28046',
          country: 'Spain',
        },
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-992020',
    title: 'Mr.',
    firstName: 'Marcus',
    lastName: 'Vance',
    birthDate: '1971-08-19',
    gender: 'Male',
    nationality: 'Canada',
    remarks: 'Permanent Do Not Rent restriction active. Blacklisted property-wide due to malicious damage.',
    dnrStatus: 'blocked',
    dnrReason: 'Severe property damage to Room 218 bathroom fixtures and threatening behavior to front desk staff. Police report filed.',
    incidentRef: 'INC-2025-1104',
    isVip: false,
    createdDate: '04-Nov-2025',
    totalStays: 1,
    totalNights: 1,
    totalSpend: 320,
    lastVisit: '04-Nov-2025',
    lastRoom: 'Room 218 (Standard King)',
    inHouse: false,
    contacts: [
      {
        id: 'CNT-992020-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+1 (416) 555-0144',
        countryCode: '+1',
        email: 'mvance.toronto@sympatico.ca',
        folioDispatch: false,
        addressType: 'Primary Residence',
        street: '340 Bay Street',
        city: 'Toronto',
        state: 'ON',
        zip: 'M5H 2S6',
        country: 'Canada',
      },
    ],
    documents: [
      {
        id: 'DOC-992020-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'CAN-KC928104',
        validTill: '2028-01-15',
        nameOnDocument: 'MARCUS EDWARD VANCE',
        issuedBy: 'Passport Canada',
        issuePlace: 'Ottawa, Canada',
        registeredAddress: {
          street: '340 Bay Street',
          city: 'Toronto',
          state: 'ON',
          zip: 'M5H 2S6',
          country: 'Canada',
        },
        isOcrVerified: true,
      },
    ],
  },
];

export const INITIAL_CATEGORIES: ContactCategory[] = [
  {
    id: 'cat-1',
    name: 'Corporate Partner',
    badgeColor: 'blue',
    linkedAccountsCount: 298,
    description: 'Direct contracted enterprise accounts with negotiated corporate rates, master billing, and net-30 folio dispatch privileges.',
    defaultCreditTerms: 'Net 30 Days',
    isLocked: true,
  },
  {
    id: 'cat-2',
    name: 'Travel Agent',
    badgeColor: 'emerald',
    linkedAccountsCount: 184,
    description: 'IATA & ARC certified travel management companies, wholesale intermediaries, and retail agencies receiving 10% commission.',
    defaultCreditTerms: 'Net 15 Days',
    isLocked: true,
  },
  {
    id: 'cat-3',
    name: 'Direct Corporate',
    badgeColor: 'indigo',
    linkedAccountsCount: 160,
    description: 'Local and regional commercial businesses with recurring weekly or monthly individual room stays on direct billing terms.',
    defaultCreditTerms: 'Net 30 Days',
    isLocked: true,
  },
  {
    id: 'cat-4',
    name: 'Vendor / Supplier',
    badgeColor: 'amber',
    linkedAccountsCount: 92,
    description: 'Contracted property service providers, food & beverage purveyors, maintenance contractors, and amenity logistics vendors.',
    defaultCreditTerms: 'Net 60 Days',
    isLocked: true,
  },
  {
    id: 'cat-5',
    name: 'Government / Diplomatic',
    badgeColor: 'purple',
    linkedAccountsCount: 37,
    description: 'Official state department consulates, embassy delegations, federal agencies, and international diplomatic corps accounts.',
    defaultCreditTerms: 'Direct Folio / Embassy Voucher',
    isLocked: true,
  },
  {
    id: 'cat-6',
    name: 'Wholesaler / Tour Operator',
    badgeColor: 'rose',
    linkedAccountsCount: 0,
    description: 'Tour operators holding contracted seasonal allotment allocations and dynamic FIT voucher inventory arrangements.',
    defaultCreditTerms: 'Net 45 Days',
    isLocked: false,
  },
];

export const INITIAL_COMMERCIAL_CONTACTS: CommercialContact[] = [
  {
    id: 'CNT-88204',
    fullName: 'Arthur Pendelton',
    designation: 'VP Global Corporate Travel',
    associatedCompany: 'Apex Global Corp',
    categoryId: 'cat-1',
    categoryName: 'Corporate Partner',
    categoryColor: 'blue',
    taxPin: 'EIN-94-3829104',
    birthDate: '1976-05-18',
    accountManager: 'Rachel Vance (Senior Key Account Dir)',
    status: 'active',
    contractStatus: 'Active SLA',
    contacts: [
      {
        id: 'ch-01',
        isPrimary: true,
        type: 'Corporate HQ / Executive Liaison',
        phone: '+1 (212) 555-0198',
        countryCode: '+1',
        email: 'arthur.pendelton@apexglobal.com',
        addressType: 'Corporate HQ',
        street: '1221 Avenue of the Americas, 48th Fl',
        city: 'New York',
        state: 'NY',
        zip: '10020',
        country: 'United States',
      },
      {
        id: 'ch-02',
        isPrimary: false,
        type: 'Regional Operations & Dispatch',
        phone: '+1 (415) 555-0812',
        countryCode: '+1',
        email: 'travel-ops@apexglobal.com',
        addressType: 'Regional Branch',
        street: '555 California St, Suite 2200',
        city: 'San Francisco',
        state: 'CA',
        zip: '94104',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'doc-01',
        documentType: 'Master Service Agreement (MSA)',
        documentNumber: 'MSA-APX-2025-09',
        validTill: '2027-12-31',
        status: 'Verified • Current',
        fileAttachmentName: 'Apex_Global_Master_Service_Agreement_2025.pdf',
      },
      {
        id: 'doc-02',
        documentType: 'Corporate Tax Exemption Certificate (W-9)',
        documentNumber: 'W9-943829104',
        validTill: '2026-12-31',
        status: 'Verified • Current',
        fileAttachmentName: 'Apex_Corp_Form_W9_Signed.pdf',
      },
    ],
  },
  {
    id: 'CNT-88205',
    fullName: 'Sarah Jenkins',
    designation: 'Global Alliance Director',
    associatedCompany: 'Horizon Travel Intermediaries',
    categoryId: 'cat-2',
    categoryName: 'Travel Agent',
    categoryColor: 'emerald',
    taxPin: 'EIN-12-8849102',
    birthDate: '1982-10-12',
    accountManager: 'David Liu (Intermediary Partnerships)',
    status: 'active',
    contractStatus: 'Annual Preferred',
    contacts: [
      {
        id: 'ch-03',
        isPrimary: true,
        type: 'Agency Central Reservations',
        phone: '+1 (800) 555-9481',
        countryCode: '+1',
        email: 'bookings@horizontravel.com',
        addressType: 'Corporate Office',
        street: '800 Michigan Ave, Suite 1500',
        city: 'Chicago',
        state: 'IL',
        zip: '60611',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'doc-03',
        documentType: 'IATA Travel Agency Accreditation',
        documentNumber: 'IATA-09482104',
        validTill: '2028-06-30',
        status: 'Verified • Current',
        fileAttachmentName: 'IATA_Accreditation_Certificate_2024.pdf',
      },
    ],
  },
  {
    id: 'CNT-88206',
    fullName: 'Robert Chen',
    designation: 'Procurement Lead',
    associatedCompany: 'OmniSupply Linen & Hospitality Co',
    categoryId: 'cat-4',
    categoryName: 'Vendor / Supplier',
    categoryColor: 'amber',
    taxPin: 'EIN-88-2910481',
    birthDate: '1979-02-14',
    accountManager: 'Operations Procurement Desk',
    status: 'active',
    contractStatus: 'Vendor Master',
    contacts: [
      {
        id: 'ch-04',
        isPrimary: true,
        type: 'Supply Logistics Dispatch',
        phone: '+1 (312) 555-3891',
        countryCode: '+1',
        email: 'orders@omnisupply-hotel.com',
        addressType: 'Warehouse & Logistics Facility',
        street: '4400 Industrial Way, Bldg 4',
        city: 'Des Plaines',
        state: 'IL',
        zip: '60018',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'doc-04',
        documentType: 'Commercial Supply & Delivery Master Contract',
        documentNumber: 'CTR-OMNI-2024-44',
        validTill: '2027-04-30',
        status: 'Verified • Current',
        fileAttachmentName: 'OmniSupply_Vendor_Agreement.pdf',
      },
    ],
  },
  {
    id: 'CNT-88207',
    fullName: 'Claire Delacroix',
    designation: 'Diplomatic Protocol Liaison',
    associatedCompany: 'Consulate General of France',
    categoryId: 'cat-5',
    categoryName: 'Government / Diplomatic',
    categoryColor: 'purple',
    taxPin: 'DIP-FR-772910',
    accountManager: 'Executive Protocol Relations',
    status: 'active',
    contractStatus: 'Active SLA',
    contacts: [
      {
        id: 'ch-05',
        isPrimary: true,
        type: 'Consular Protocol Office',
        phone: '+1 (212) 606-3600',
        countryCode: '+1',
        email: 'protocole.new-york-fslt@diplomatie.gouv.fr',
        addressType: 'Consulate Building',
        street: '934 Fifth Avenue',
        city: 'New York',
        state: 'NY',
        zip: '10021',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'doc-05',
        documentType: 'Vienna Convention Diplomatic Tax Exemption Letter',
        documentNumber: 'TAX-EX-DIP-FR-902',
        validTill: '2030-12-31',
        status: 'Verified • Current',
        fileAttachmentName: 'French_Consulate_Tax_Exemption_Form.pdf',
      },
    ],
  },
  {
    id: 'CNT-88208',
    fullName: 'Michael Sterling',
    designation: 'Corporate Travel Director',
    associatedCompany: 'Vanguard Dynamics Ltd',
    categoryId: 'cat-3',
    categoryName: 'Direct Corporate',
    categoryColor: 'indigo',
    taxPin: 'EIN-55-9921048',
    accountManager: 'Rachel Vance (Senior Key Account Dir)',
    status: 'active',
    contractStatus: 'Expiring Q4',
    contacts: [
      {
        id: 'ch-06',
        isPrimary: true,
        type: 'Corporate Travel Administration',
        phone: '+1 (617) 555-8291',
        countryCode: '+1',
        email: 'travel@vanguard-dynamics.com',
        addressType: 'Corporate Headquarters',
        street: '100 Federal Street, 32nd Floor',
        city: 'Boston',
        state: 'MA',
        zip: '02110',
        country: 'United States',
      },
    ],
    documents: [
      {
        id: 'doc-06',
        documentType: 'Corporate Preferred Lodging Agreement',
        documentNumber: 'AGR-VGD-2024-11',
        validTill: '2026-11-30',
        status: 'Expiring Soon',
        fileAttachmentName: 'Vanguard_Lodging_Rate_Agreement.pdf',
      },
    ],
  },
];

export const INITIAL_LOST_FOUND: LostFoundItem[] = [
  {
    id: 'LF-2026-0841',
    surrenderType: 'found',
    dispositionStatus: 'open',
    itemName: 'Montblanc Meisterstück Fountain Pen',
    category: 'Writing Instruments / Valuables',
    color: 'Obsidian Black & Gold',
    colorHex: '#1a1a1a',
    characteristics: 'Black precious resin barrel, 14K gold-coated nib with custom initials ERH engraved on clip. Excellent condition with blue ink cartridge intact.',
    serialNumber: 'MB-GER-89421A',
    locationFound: 'Executive Lounge 14F • North Workstation 03',
    storageVault: 'VAULT-A-04 • High Security Safe',
    dateLogged: '2026-09-14 14:22',
    reportedBy: 'Marcus Vance (Lead Concierge #482)',
    guestId: 'GST-992014',
    guestName: 'Dr. Elena Rostova-Hughes',
    roomNumber: 'Room 402',
    folioNumber: 'Folio #F-88102',
    custodyNotes: 'Secured in sealed tamper-evident custody bag #TB-88421. Guest notified via mobile SMS and front desk flag active.',
    retentionDaysRemaining: 78,
  },
  {
    id: 'LF-2026-0840',
    surrenderType: 'found',
    dispositionStatus: 'returned',
    itemName: 'Apple MacBook Pro 16" Space Gray',
    category: 'Electronics / Audio',
    color: 'Space Gray Metallic',
    colorHex: '#333333',
    characteristics: 'Model A2780 with dual USB-C MagSafe cable and leather sleeve. Serial matched corporate IT asset database.',
    serialNumber: 'C02G9014MD6R',
    locationFound: 'Conference Room C (3rd Floor)',
    storageVault: 'VAULT-B-01 • Secure IT Storage',
    dateLogged: '2026-09-13 18:40',
    reportedBy: 'David Miller (Security Guard #108)',
    guestId: 'CNT-88204',
    guestName: 'Arthur Pendelton',
    folioNumber: 'Folio #F-88094',
    custodyNotes: 'Claimed by Arthur Pendelton on 14-Sep-2026 09:15 after verifying device passcode and signing surrender voucher #SV-491.',
    retentionDaysRemaining: 0,
  },
  {
    id: 'LF-2026-0839',
    surrenderType: 'lost',
    dispositionStatus: 'open',
    itemName: 'Diamond Solitaire Tennis Bracelet',
    category: 'Jewelry / Watch',
    color: 'Platinum & Diamond',
    colorHex: '#e5e7eb',
    characteristics: '18K white gold / platinum band with 42 round brilliant cut diamonds. Safety clasp reported loose by guest.',
    locationFound: 'Spa Treatment Room 2 / Hydrotherapy Pool Area',
    storageVault: 'SEARCH-ACTIVE • Incident Broadcast #SEC-99',
    dateLogged: '2026-09-13 11:15',
    reportedBy: 'Reception Desk (Guest Report Filed)',
    guestId: 'GST-992019',
    guestName: 'Sofia Alvarez',
    roomNumber: 'Room 810',
    folioNumber: 'Folio #F-88062',
    custodyNotes: 'Guest reported missing item after spa session. Spa staff and housekeeping team conducted thorough search; security review ongoing.',
    retentionDaysRemaining: 89,
  },
  {
    id: 'LF-2026-0838',
    surrenderType: 'found',
    dispositionStatus: 'open',
    itemName: 'Ray-Ban Aviator Sunglasses (Gold Frame)',
    category: 'Apparel / Outerwear',
    color: 'Gold Frame & Green G-15 Lens',
    colorHex: '#eab308',
    characteristics: 'Classic Aviator RB3025 with polarized green lenses and tan leather hard case.',
    serialNumber: 'RB3025-001/58',
    locationFound: 'Poolside Cabana #4 • Sun Lounge',
    storageVault: 'LOCKER-12 • Lost & Found Bin B',
    dateLogged: '2026-09-12 16:30',
    reportedBy: 'Carlos Mendez (Pool Attendant #310)',
    custodyNotes: 'Found on table side after cabana turnover. Tagged and stored.',
    retentionDaysRemaining: 88,
  },
  {
    id: 'LF-2026-0837',
    surrenderType: 'found',
    dispositionStatus: 'returned',
    itemName: 'Rimowa Classic Aluminum Carry-on Luggage',
    category: 'Luggage / Bags',
    color: 'Brushed Silver Aluminum',
    colorHex: '#94a3b8',
    characteristics: 'Four multiwheel suitcase with TSA combination lock. Baggage tag from Frankfurt Airport (FRA).',
    locationFound: 'Front Porch / Valet Bell Stand',
    storageVault: 'LUGGAGE-HOLD-02',
    dateLogged: '2026-09-11 09:10',
    reportedBy: 'Thomas Wright (Head Bellman)',
    guestId: 'GST-992015',
    guestName: 'Klaus Schulze',
    roomNumber: 'Room 804',
    custodyNotes: 'Guest left luggage behind during morning transfer; courier arranged to German Embassy and confirmed received.',
    retentionDaysRemaining: 0,
  },
  {
    id: 'LF-2026-0836',
    surrenderType: 'found',
    dispositionStatus: 'returned',
    itemName: 'Leather Passport Wallet with Foreign Currency',
    category: 'Writing Instruments / Valuables',
    color: 'Cognac Brown Calfskin',
    colorHex: '#78350f',
    characteristics: 'Contains €450 cash, boarding pass stubs, and business cards.',
    locationFound: 'Lobby Bar Booth 6',
    storageVault: 'VAULT-A-01 • Safe Deposit',
    dateLogged: '2026-09-10 22:15',
    reportedBy: 'Night Bartender (Shift Lead)',
    guestName: 'Klaus Schulze',
    custodyNotes: 'Returned to guest following morning at front desk with security sign-off.',
    retentionDaysRemaining: 0,
  },
  {
    id: 'LF-2026-0835',
    surrenderType: 'found',
    dispositionStatus: 'discarded',
    itemName: 'Sony Wireless Noise-Canceling Headphones WH-1000XM5',
    category: 'Electronics / Audio',
    color: 'Midnight Silver',
    colorHex: '#cbd5e1',
    characteristics: 'Headband cracked with cosmetic scratches. No charging cable.',
    locationFound: 'Fitness Center Treadmill #3',
    storageVault: 'SALVAGE-VAULT-09',
    dateLogged: '2026-06-12 07:45',
    reportedBy: 'Gym Staff Attendant',
    custodyNotes: '90-day statutory retention expired without claimant. Disposed according to hotel salvage & local charity donation protocol.',
    retentionDaysRemaining: 0,
  },
];

export const SAMPLE_GUESTS = INITIAL_GUESTS;
export const SAMPLE_COMMERCIAL_CONTACTS = INITIAL_COMMERCIAL_CONTACTS;
export const INITIAL_CONTACT_CATEGORIES = INITIAL_CATEGORIES;
export const SAMPLE_CONTACT_CATEGORIES = INITIAL_CATEGORIES;
export const SAMPLE_LOST_FOUND_ITEMS = INITIAL_LOST_FOUND;

export const SURAT_GUESTS: GuestRecord[] = [
  {
    id: 'GST-STVMC-101',
    title: 'Mr.',
    firstName: 'Rajesh',
    middleName: 'K.',
    lastName: 'Mehta',
    suffix: '',
    birthDate: '1975-08-15',
    gender: 'Male',
    nationality: 'India',
    company: 'Reliance Industries Ltd',
    designation: 'Managing Director - Petrochemicals',
    department: 'Corporate Executive',
    remarks: 'Diamond Club VIP. Prefers high-floor room overlooking Tapi River, vegetarian Jain breakfast, green tea in room on arrival.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'VIP Tier 1 • Marriott Bonvoy Titanium',
    createdDate: '12-Jan-2023',
    totalStays: 28,
    totalNights: 84,
    totalSpend: 1120000,
    lastVisit: '10-Jun-2026',
    lastRoom: 'Suite 902 (Tapi River Suite)',
    inHouse: true,
    contacts: [
      {
        id: 'CNT-STVMC-101-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+91 98250 11234',
        countryCode: '+91',
        email: 'rajesh.mehta@reliance-exec.in',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: '42 Ambience Tower, Dumas Road',
        city: 'Surat',
        state: 'Gujarat',
        zip: '395007',
        country: 'India',
      },
    ],
    documents: [
      {
        id: 'DOC-STVMC-101-01',
        isPrimary: true,
        documentType: 'Aadhaar Card',
        documentNumber: 'XXXX-XXXX-8421',
        validTill: '2035-12-31',
        nameOnDocument: 'RAJESH K MEHTA',
        issuedBy: 'UIDAI - Government of India',
        issuePlace: 'Gujarat, India',
        registeredAddress: {
          street: '42 Ambience Tower, Dumas Road',
          city: 'Surat',
          state: 'Gujarat',
          zip: '395007',
          country: 'India',
        },
        remarks: 'Biometric UIDAI e-verification verified at check-in.',
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-STVMC-102',
    title: 'Ms.',
    firstName: 'Priya',
    middleName: '',
    lastName: 'Sharma',
    suffix: '',
    birthDate: '1988-11-22',
    gender: 'Female',
    nationality: 'India',
    company: 'Tata Consultancy Services',
    designation: 'Principal Solutions Architect',
    department: 'Enterprise Cloud Solutions',
    remarks: 'Late checkout requested for 16:00 PM due to evening flight to Mumbai. Twin pillows requested.',
    dnrStatus: 'none',
    isVip: false,
    vipTier: 'Marriott Bonvoy Gold Elite',
    createdDate: '04-Feb-2024',
    totalStays: 9,
    totalNights: 22,
    totalSpend: 295000,
    lastVisit: '22-May-2026',
    lastRoom: 'Room 508 (Executive Twin)',
    inHouse: true,
    contacts: [
      {
        id: 'CNT-STVMC-102-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+91 97129 44321',
        countryCode: '+91',
        email: 'priya.sharma@tcs.com',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'B-604, Godrej Garden City, SG Highway',
        city: 'Ahmedabad',
        state: 'Gujarat',
        zip: '382470',
        country: 'India',
      },
    ],
    documents: [
      {
        id: 'DOC-STVMC-102-01',
        isPrimary: true,
        documentType: 'Passport',
        documentNumber: 'IND-Z8472910',
        validTill: '2032-05-18',
        nameOnDocument: 'PRIYA SHARMA',
        issuedBy: 'Passport Office Ahmedabad',
        issuePlace: 'Ahmedabad, India',
        registeredAddress: {
          street: 'B-604, Godrej Garden City, SG Highway',
          city: 'Ahmedabad',
          state: 'Gujarat',
          zip: '382470',
          country: 'India',
        },
        remarks: 'Physical passport inspected and copied.',
        isOcrVerified: true,
      },
    ],
  },
  {
    id: 'GST-STVMC-103',
    title: 'Mr.',
    firstName: 'Amit',
    middleName: 'B.',
    lastName: 'Patel',
    suffix: '',
    birthDate: '1982-03-09',
    gender: 'Male',
    nationality: 'India',
    company: 'Surat Diamond Bourse (SDB)',
    designation: 'Managing Partner',
    department: 'Diamond Trading & Exports',
    remarks: 'Requires in-room digital safe calibration for high-value gem samples. Requires secure courier coordination.',
    dnrStatus: 'none',
    isVip: true,
    vipTier: 'VIP Tier 2 • Ambassador Elite',
    createdDate: '18-Aug-2021',
    totalStays: 41,
    totalNights: 120,
    totalSpend: 1980000,
    lastVisit: '15-Jun-2026',
    lastRoom: 'Suite 1001 (Presidential Suite)',
    inHouse: false,
    contacts: [
      {
        id: 'CNT-STVMC-103-01',
        isPrimary: true,
        contactType: 'Mobile / Personal',
        phone: '+91 98980 77654',
        countryCode: '+91',
        email: 'amit.patel@sdb-diamonds.in',
        folioDispatch: true,
        addressType: 'Primary Residence',
        street: 'Plot 12, Diamond City Park, Khajod',
        city: 'Surat',
        state: 'Gujarat',
        zip: '395007',
        country: 'India',
      },
    ],
    documents: [
      {
        id: 'DOC-STVMC-103-01',
        isPrimary: true,
        documentType: 'PAN Card',
        documentNumber: 'ABCPK1234F',
        validTill: '2099-12-31',
        nameOnDocument: 'AMIT BHIKHUBHAI PATEL',
        issuedBy: 'Income Tax Department of India',
        issuePlace: 'Surat, India',
        registeredAddress: {
          street: 'Plot 12, Diamond City Park, Khajod',
          city: 'Surat',
          state: 'Gujarat',
          zip: '395007',
          country: 'India',
        },
        remarks: 'Permanent Account Number verified against GST billing.',
        isOcrVerified: true,
      },
    ],
  },
];

export const SURAT_COMMERCIAL_CONTACTS: CommercialContact[] = [
  {
    id: 'CC-STVMC-01',
    companyName: 'Surat Diamond Bourse Corporate Travel',
    accountCode: 'CORP-SDB-2026',
    category: 'Corporate Client',
    status: 'active',
    primaryContactPerson: 'Chirag Shah',
    designation: 'Director of Vendor Relations',
    contractStart: '2026-01-01',
    contractEnd: '2026-12-31',
    contractRateCode: 'SDB-CORP-SPECIAL',
    creditLimit: 5000000,
    paymentTerms: 'Net 30 Days Direct Billing',
    gstNumber: '24AABCS1429B1Z8',
    panNumber: 'AABCS1429B',
    phone: '+91 (261) 298-0000',
    email: 'travel@suratdiamondbourse.org',
    city: 'Surat',
    state: 'Gujarat',
    country: 'India',
    annualNightsCommitment: 850,
    productionNightsYtd: 420,
    productionRevenueYtd: 5460000,
    assignedSalesManager: 'Priya Shah (Corporate Sales Lead)',
  },
  {
    id: 'CC-STVMC-02',
    companyName: 'Larsen & Toubro Hazira Complex',
    accountCode: 'CORP-LT-HAZIRA',
    category: 'Corporate Client',
    status: 'active',
    primaryContactPerson: 'Sanjay Deshmukh',
    designation: 'General Manager - Administration',
    contractStart: '2026-01-01',
    contractEnd: '2026-12-31',
    contractRateCode: 'LT-HAZIRA-CORP',
    creditLimit: 3500000,
    paymentTerms: 'Net 15 Days Direct Billing',
    gstNumber: '24AAACL0140P1ZQ',
    panNumber: 'AAACL0140P',
    phone: '+91 (261) 286-5000',
    email: 'admin.hazira@larsentoubro.com',
    city: 'Hazira, Surat',
    state: 'Gujarat',
    country: 'India',
    annualNightsCommitment: 600,
    productionNightsYtd: 310,
    productionRevenueYtd: 4185000,
    assignedSalesManager: 'Priya Shah (Corporate Sales Lead)',
  },
];

export const SURAT_LOST_FOUND_ITEMS: LostFoundItem[] = [
  {
    id: 'LF-STVMC-001',
    surrenderType: 'found',
    dispositionStatus: 'stored',
    itemName: 'Apple iPad Pro 12.9" with Magnetic Pencil',
    category: 'Electronics / Tablets',
    color: 'Space Gray',
    colorHex: '#475569',
    characteristics: 'In navy blue Smart Folio case. Lock screen shows corporate Reliance logo.',
    locationFound: 'Tapi Riverside Terrace Table #8',
    storageVault: 'FRONT-DESK-SAFE-01',
    dateLogged: '2026-06-28 21:30',
    reportedBy: 'Karan Dave (Restaurant Supervisor)',
    guestName: 'Rajesh Mehta',
    custodyNotes: 'Secured in front office safe. Guest notified via WhatsApp and SMS.',
    retentionDaysRemaining: 60,
  },
  {
    id: 'LF-STVMC-002',
    surrenderType: 'found',
    dispositionStatus: 'stored',
    itemName: 'Montblanc Meisterstück Rollerball Pen (Gold Trim)',
    category: 'Writing Instruments / Valuables',
    color: 'Precious Black Resin',
    colorHex: '#0f172a',
    characteristics: 'Engraved with initials "A.B.P." on pocket clip.',
    locationFound: 'Executive Boardroom B',
    storageVault: 'SECURITY-VAULT-MAIN',
    dateLogged: '2026-06-25 14:15',
    reportedBy: 'Bhavna Ben (Housekeeping Executive)',
    guestName: 'Amit Patel',
    custodyNotes: 'High-value item logged in secure register.',
    retentionDaysRemaining: 75,
  },
];

