import { HousekeepingGroup, HousekeepingMember, HousekeepingTask, UnassignedRoom, AttendantAssignment } from './types';

export const INITIAL_GROUPS: HousekeepingGroup[] = [
  {
    id: 'grp-1',
    name: 'North Tower Morning Squad',
    shift: 'morning',
    shiftHours: 'Shift A • 07:00 - 15:30',
    badge: 'Full Crew',
    badgeType: 'default',
    description: 'Primary daily stay-over service and turnover cleans across high-tier north wing.',
    memberInitials: ['AK', 'MR', 'SL'],
    membersCount: 8,
    roomCount: 36,
    roomScope: '(Floors 1-4 North)',
    isProtected: true,
    iconName: 'Sun',
  },
  {
    id: 'grp-2',
    name: 'Floor 1-4 Daily Turn',
    shift: 'morning',
    shiftHours: 'Shift A • 07:30 - 16:00',
    description: 'Standard double and queen units checkout turnaround cycle.',
    memberInitials: ['TC', 'PL'],
    membersCount: 6,
    roomCount: 28,
    roomScope: '(South Wing)',
    isProtected: true,
    iconName: 'Building2',
  },
  {
    id: 'grp-3',
    name: 'Executive Suites Team',
    shift: 'morning',
    shiftHours: 'Shift A • 08:00 - 16:30',
    badge: 'VIP Priority',
    badgeType: 'vip',
    description: 'Premium penthouses, presidential suites and VIP club floors inspection & prep.',
    memberInitials: ['DA', 'RH'],
    membersCount: 6,
    roomCount: 24,
    roomScope: '(Floors 12-14)',
    isProtected: true,
    iconName: 'Crown',
  },
  {
    id: 'grp-4',
    name: 'Deep Clean & Sanitization Unit',
    shift: 'specialized',
    shiftHours: 'Shift C • 21:00 - 05:00',
    badge: 'Rotational',
    badgeType: 'rotational',
    description: 'Carpet shampooing, mattress deep sanitation, drapery steam and vent maintenance.',
    memberInitials: ['BM'],
    membersCount: 4,
    roomCount: 10,
    roomScope: '(Cycle B-Weekly)',
    isProtected: true,
    iconName: 'Sparkles',
  },
  {
    id: 'grp-5',
    name: 'Late Evening Turndown Crew',
    shift: 'afternoon',
    shiftHours: 'Shift B • 17:00 - 22:30',
    description: 'Linen replenishment, evening turndown treats, ice refilling, and towel replenishment.',
    memberInitials: ['JW'],
    membersCount: 8,
    roomCount: 44,
    roomScope: '(Occupied Club)',
    isProtected: true,
    iconName: 'Moon',
  },
  {
    id: 'grp-6',
    name: 'Public Area & Lobby Attendants',
    shift: 'specialized',
    shiftHours: 'Special • Unassigned',
    badge: 'Draft Group',
    badgeType: 'draft',
    description: 'Newly created setup for reception lounge, public restrooms and mezzanine walkways.',
    memberInitials: [],
    membersCount: 0,
    roomCount: 0,
    roomScope: '0 Assigned Units',
    isProtected: false,
    iconName: 'Building',
  },
];

export const INITIAL_TASKS: HousekeepingTask[] = [
  {
    id: 'HSK-101',
    seq: 1,
    name: 'Stripping & Linen Removal',
    code: 'HSK-101',
    description: 'Strip pillowcases, duvets, and soiled bathroom toweling',
    durationMinutes: 10,
    autoVacantDirty: true,
    isTemplateDefault: true,
  },
  {
    id: 'HSK-102',
    seq: 2,
    name: 'Bed Making & Fresh Linen',
    code: 'HSK-102',
    description: 'Hospital corners, insert fresh Egyptian cotton sets & runners',
    durationMinutes: 15,
    autoVacantDirty: true,
    isTemplateDefault: true,
  },
  {
    id: 'HSK-103',
    seq: 3,
    name: 'Bathroom Full Sanitization',
    code: 'HSK-103',
    description: 'Glass descaling, vanity wipe, high-grade hospital disinfectant',
    durationMinutes: 20,
    autoVacantDirty: true,
    isTemplateDefault: true,
  },
  {
    id: 'HSK-104',
    seq: 4,
    name: 'High-Touch Dusting & Surface Wipe',
    code: 'HSK-104',
    description: 'TV remotes, telephone, handles, bedside electronics',
    durationMinutes: 15,
    autoVacantDirty: true,
    isTemplateDefault: true,
  },
  {
    id: 'HSK-105',
    seq: 5,
    name: 'Vacuuming & Floor Mopping',
    code: 'HSK-105',
    description: 'Carpet edge detailing and hard-floor neutral damp mop',
    durationMinutes: 15,
    autoVacantDirty: true,
    isTemplateDefault: false,
  },
  {
    id: 'HSK-106',
    seq: 6,
    name: 'Minibar & In-Room Amenities Restock',
    code: 'HSK-106',
    description: 'Mineral water, coffee capsules, luxury bath soaps, vanity packs',
    durationMinutes: 10,
    autoVacantDirty: false,
    isTemplateDefault: true,
  },
  {
    id: 'HSK-107',
    seq: 7,
    name: 'Deep Carpet Shampoo & Ozone Treatment',
    code: 'HSK-107',
    description: 'Extraction steam cycle, anti-microbial seal, odor purge',
    durationMinutes: 45,
    autoVacantDirty: false,
    isTemplateDefault: false,
  },
  {
    id: 'HSK-108',
    seq: 8,
    name: 'Balcony & Glass Window Wash',
    code: 'HSK-108',
    description: 'Exterior glazing squeegee, railing scrub, patio tile sweep',
    durationMinutes: 20,
    autoVacantDirty: false,
    isTemplateDefault: false,
  },
];

export const INITIAL_MEMBERS: HousekeepingMember[] = [
  {
    id: 'mem-1',
    empId: 'EMP-4091',
    name: 'Elena Rostova',
    role: 'Sr. Room Attendant',
    initials: 'ER',
    isOnDuty: true,
    assignedTasks: ['HSK-101', 'HSK-102', 'HSK-103', 'HSK-104', 'HSK-105', 'HSK-106'],
  },
  {
    id: 'mem-2',
    empId: 'EMP-4102',
    name: 'Marcus Chen',
    role: 'Floor Attendant',
    initials: 'MC',
    isOnDuty: true,
    assignedTasks: ['HSK-101', 'HSK-102', 'HSK-103', 'HSK-104', 'HSK-105'],
  },
  {
    id: 'mem-3',
    empId: 'EMP-4119',
    name: 'Amara Diallo',
    role: 'Floor Attendant',
    initials: 'AD',
    isOnDuty: true,
    assignedTasks: ['HSK-101', 'HSK-102', 'HSK-103', 'HSK-104', 'HSK-105'],
  },
  {
    id: 'mem-4',
    empId: 'EMP-3882',
    name: 'Carlos Mendez',
    role: 'Deep Clean Specialist',
    initials: 'CM',
    isOnDuty: true,
    assignedTasks: ['HSK-103', 'HSK-107', 'HSK-108'],
  },
  {
    id: 'mem-5',
    empId: 'EMP-4204',
    name: 'Amina Al-Mansoor',
    role: 'Floor Attendant',
    initials: 'AA',
    isOnDuty: false,
    shiftStart: 'Starts 07:30',
    assignedTasks: ['HSK-101', 'HSK-102', 'HSK-103', 'HSK-104', 'HSK-105', 'HSK-106'],
  },
  {
    id: 'mem-6',
    empId: 'EMP-4211',
    name: 'David Kim',
    role: 'Sanitization Tech',
    initials: 'DK',
    isOnDuty: true,
    assignedTasks: ['HSK-101', 'HSK-103', 'HSK-104', 'HSK-105', 'HSK-107'],
  },
  {
    id: 'mem-7',
    empId: 'EMP-4309',
    name: 'Sophia Rossi',
    role: 'Amenity Runner',
    initials: 'SR',
    isOnDuty: true,
    assignedTasks: ['HSK-104', 'HSK-106', 'HSK-108'],
  },
  {
    id: 'mem-8',
    empId: 'EMP-4328',
    name: 'Liam Gallagher',
    role: 'Floor Attendant',
    initials: 'LG',
    isOnDuty: true,
    assignedTasks: ['HSK-101', 'HSK-102', 'HSK-103', 'HSK-104', 'HSK-105'],
  },
];

export const INITIAL_UNASSIGNED_ROOMS: UnassignedRoom[] = [
  {
    id: 'card-101',
    roomNumber: '101',
    roomType: 'DLXK',
    status: 'VD',
    statusLabel: 'VACANT DIRTY',
    priorityLabel: 'Checkout 11:00 AM • High Priority',
    estMinutes: 30,
  },
  {
    id: 'card-104',
    roomNumber: '104',
    roomType: 'DLXK',
    status: 'VD',
    statusLabel: 'VACANT DIRTY',
    note: 'Next Guest ETA: 14:00',
    estMinutes: 25,
  },
  {
    id: 'card-108',
    roomNumber: '108',
    roomType: 'EXST',
    status: 'OD',
    statusLabel: 'OCCUPIED DIRTY',
    isVip: true,
    vipTier: 'VIP 1',
    note: 'Special Turnaround Amenities',
    estMinutes: 40,
  },
  {
    id: 'card-202',
    roomNumber: '202',
    roomType: 'SUPQ',
    status: 'VD',
    statusLabel: 'VACANT DIRTY',
    note: 'Floor 2 • Standard Refresh',
    estMinutes: 20,
  },
  {
    id: 'card-205',
    roomNumber: '205',
    roomType: 'SUPQ',
    status: 'SO',
    statusLabel: 'STAYOVER CLEAN',
    note: 'Towel exchange requested',
    estMinutes: 20,
  },
  {
    id: 'card-210',
    roomNumber: '210',
    roomType: 'DLXK',
    status: 'VD',
    statusLabel: 'VACANT DIRTY',
    note: 'Floor 2 • West Corridor',
    estMinutes: 25,
  },
  {
    id: 'card-301',
    roomNumber: '301',
    roomType: 'EXST',
    status: 'OD',
    statusLabel: 'OCCUPIED DIRTY',
    priorityLabel: 'Late Service Request (13:00)',
    estMinutes: 30,
  },
  {
    id: 'card-305',
    roomNumber: '305',
    roomType: 'DLXK',
    status: 'VD',
    statusLabel: 'VACANT DIRTY',
    note: 'Checkout 10:30 AM',
    estMinutes: 25,
  },
  {
    id: 'card-312',
    roomNumber: '312',
    roomType: 'PRMS',
    status: 'VD',
    statusLabel: 'URGENT VD',
    isVip: true,
    vipTier: 'VIP ULTRA',
    priorityLabel: 'Presidential Suite • Turnaround',
    estMinutes: 50,
  },
  {
    id: 'card-402',
    roomNumber: '402',
    roomType: 'DLXK',
    status: 'TOUCH',
    statusLabel: 'TOUCH-UP REQ',
    note: 'Pre-arrival linen fluff & minibar check',
    estMinutes: 15,
  },
];

export const INITIAL_ATTENDANT_ASSIGNMENTS: AttendantAssignment[] = [
  {
    attendantId: 'elena',
    empId: 'EMP-4091',
    name: 'Elena Rostova',
    role: 'Sr. Attendant',
    initials: 'ER',
    focusFloor: 'Floor 1 Focus',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '102', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '103', status: 'VCI', type: 'DLXK', minutes: 20 },
      { roomNumber: '105', status: 'SO', type: 'SUPQ', minutes: 25 },
      { roomNumber: '106', status: 'OD', type: 'EXST', minutes: 40 },
      { roomNumber: '107', status: 'VD', type: 'DLXK', minutes: 35 },
    ],
  },
  {
    attendantId: 'marcus',
    empId: 'EMP-4102',
    name: 'Marcus Chen',
    role: 'Attendant',
    initials: 'MC',
    focusFloor: 'Floor 2 Focus',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '201', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '203', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '204', status: 'SO', type: 'SUPQ', minutes: 25 },
      { roomNumber: '206', status: 'OD', type: 'EXST', minutes: 30 },
      { roomNumber: '208', status: 'VD', type: 'DLXK', minutes: 30 },
    ],
  },
  {
    attendantId: 'amara',
    empId: 'EMP-4115',
    name: 'Amara Diallo',
    role: 'Attendant',
    initials: 'AD',
    focusFloor: 'Floor 2 & 3',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '211', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '212', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '214', status: 'SO', type: 'SUPQ', minutes: 25 },
      { roomNumber: '215', status: 'VD', type: 'DLXK', minutes: 35 },
      { roomNumber: '216', status: 'OD', type: 'EXST', minutes: 40 },
    ],
  },
  {
    attendantId: 'carlos',
    empId: 'EMP-4140',
    name: 'Carlos Mendez',
    role: 'Floor Attendant',
    initials: 'CM',
    focusFloor: 'Floor 3',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '302', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '304', status: 'VCI', type: 'DLXK', minutes: 20 },
      { roomNumber: '306', status: 'VD', type: 'DLXK', minutes: 35 },
      { roomNumber: '308', status: 'OD', type: 'EXST', minutes: 35 },
    ],
  },
  {
    attendantId: 'amina',
    empId: 'EMP-4188',
    name: 'Amina Al-Mansoor',
    role: 'Attendant',
    initials: 'AA',
    focusFloor: 'Floor 4',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '401', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '403', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '404', status: 'SO', type: 'SUPQ', minutes: 25 },
      { roomNumber: '405', status: 'OD', type: 'EXST', minutes: 30 },
    ],
  },
  {
    attendantId: 'david',
    empId: 'EMP-4210',
    name: 'David Kim',
    role: 'Attendant',
    initials: 'DK',
    focusFloor: 'Floor 4 Focus',
    maxMinutes: 180,
    assignedRooms: [
      { roomNumber: '406', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '408', status: 'VD', type: 'DLXK', minutes: 30 },
      { roomNumber: '410', status: 'SO', type: 'SUPQ', minutes: 30 },
    ],
  },
];
